/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yxj_helloffmpeglibrary_HelloFFmpegLibrary */

#ifndef _Included_com_yxj_helloffmpeglibrary_HelloFFmpegLibrary
#define _Included_com_yxj_helloffmpeglibrary_HelloFFmpegLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yxj_helloffmpeglibrary_HelloFFmpegLibrary
 * Method:    showFFmpegInfo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yxj_helloffmpeglibrary_HelloFFmpegLibrary_showFFmpegInfo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
