/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yxj_helloffmpeglibrary_HelloFFmpegLibrary */

#ifndef _Included_com_yxj_helloffmpeglibrary_HelloFFmpegLibrary
#define _Included_com_yxj_helloffmpeglibrary_HelloFFmpegLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yxj_helloffmpeglibrary_HelloFFmpegLibrary
 * Method:    showFFmpegConfiguration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yxj_helloffmpeglibrary_HelloFFmpegLibrary_showFFmpegConfiguration
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
